### ISSUE TITLE
specify format of consensus document so that more than one language implementation of the parser can be implemented

### ISSUE THREAD

**Issue by david415** [katzenpost/docs#5]

**Comment by Yawning** [comment]
I said this on IRC, but I'll say it here as well.  The `nonvoting` authority is a placeholder primarily inteded as something to be used for testing/debugging/development.

It my mind makes zero sense to document what essentially is "JWS + JSON used in the simplest possible way" that I change based on my mood, phase of the moon, and paranoia, because I will repeatedly change the on the wire serialization, and people will be sad.

The correct thing to do here IMO is "Come up with sensible serialization format(s) that the real authority can use".

**Comment by Yawning** [comment]
I said this on IRC, but I'll say it here as well.  The `nonvoting` authority is a placeholder primarily intended as something to be used for testing/debugging/development.

It my mind makes zero sense to document what essentially is "JWS + JSON used in the simplest possible way" that I change based on my mood, phase of the moon, and paranoia, because I will repeatedly change the on the wire serialization, and people will be sad.

The correct thing to do here IMO is "Come up with sensible serialization format(s) that the real authority can use".
